//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boxer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7FFFD4")]
        public global::System.Windows.Media.Color ViewerBackgroundColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ViewerBackgroundColor"]));
            }
            set {
                this["ViewerBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color CenterPointColor {
            get {
                return ((global::System.Windows.Media.Color)(this["CenterPointColor"]));
            }
            set {
                this["CenterPointColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color PolygonColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PolygonColor"]));
            }
            set {
                this["PolygonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.Color CenterLineColor {
            get {
                return ((global::System.Windows.Media.Color)(this["CenterLineColor"]));
            }
            set {
                this["CenterLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color BorderColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColor"]));
            }
            set {
                this["BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color TrimBorderColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TrimBorderColor"]));
            }
            set {
                this["TrimBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7FFFD4")]
        public global::System.Windows.Media.Color DocumentStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["DocumentStubColor"]));
            }
            set {
                this["DocumentStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFE4C4")]
        public global::System.Windows.Media.Color FolderStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["FolderStubColor"]));
            }
            set {
                this["FolderStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF6495ED")]
        public global::System.Windows.Media.Color ImageStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ImageStubColor"]));
            }
            set {
                this["ImageStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF87CEFA")]
        public global::System.Windows.Media.Color FrameStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["FrameStubColor"]));
            }
            set {
                this["FrameStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F8FF")]
        public global::System.Windows.Media.Color PolygonStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PolygonStubColor"]));
            }
            set {
                this["PolygonStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE0FFFF")]
        public global::System.Windows.Media.Color PolygonGroupStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PolygonGroupStubColor"]));
            }
            set {
                this["PolygonGroupStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color PolygonSelectedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PolygonSelectedColor"]));
            }
            set {
                this["PolygonSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawLineArtForCenter {
            get {
                return ((bool)(this["DrawLineArtForCenter"]));
            }
            set {
                this["DrawLineArtForCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawBorder {
            get {
                return ((bool)(this["DrawBorder"]));
            }
            set {
                this["DrawBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrimToMinimalNonTransparentArea {
            get {
                return ((bool)(this["TrimToMinimalNonTransparentArea"]));
            }
            set {
                this["TrimToMinimalNonTransparentArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ZoomIndex {
            get {
                return ((int)(this["ZoomIndex"]));
            }
            set {
                this["ZoomIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::Microsoft.Xna.Framework.Vector2 CameraPos {
            get {
                return ((global::Microsoft.Xna.Framework.Vector2)(this["CameraPos"]));
            }
            set {
                this["CameraPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public float SimulationRatio {
            get {
                return ((float)(this["SimulationRatio"]));
            }
            set {
                this["SimulationRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkAllAsOpen {
            get {
                return ((bool)(this["MarkAllAsOpen"]));
            }
            set {
                this["MarkAllAsOpen"] = value;
            }
        }
    }
}
